Developer
tangriane/tangriane.github.io pull request #4
Opened 2017-11-01 19:53 UTC by tangriane

2017-11-01 23:39 UTC, andre-mendes commented on src/scss/helpers/variaveis.scss
> +$branco: #fff;
Tang, é interessante vc dar nomes mais "genericos" pras suas variaveis... por exemplo a `$cor-nav` poderia ser `$primary-color` ... pq se vc mudar a cor da sua "nav" ai fica meio cabuloso uahsAHUShuaUHS e voce tbm poderia colocar os nomes em ingles :D

2017-11-02 00:14 UTC, andre-mendes requested changes
🔥 🔥 🔥

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/contato.scss
> +   width: 100%;
Aqui voce colocou `width`e `height`2x... tem ali em cima tbm :)

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/contato.scss
> +.contato{
coloca um espaço entre `.contato` e a `{`e tbm coloca nome em ingles 💃

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/contato.scss
> +
pq esse espaço?

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/contato.scss
> +.contatc{
pq ali em cima tem `.contato` e aqui `.contact` ? ⚔️

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/contato.scss
> +}
da um talentinho nessa identaçao <3

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/contato.scss
> +.contact__h1{
acho que esse nome de classe poderia ser algo do tipo `.contact__title` .... e se vc trocar o `h1` por um `h2` ou outra coisa? :)

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/contato.scss
> +
:{D

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/contato.scss
> +.contact__p{
onte tiver esses `__p` `__h1` sascoisa, faça como comentei ali em cima :D e tbm sempre coloca espaço entre o nome da classe e a `{`

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/contato.scss
> +   color: #BEC7D5;
essa cor poderia ser uma variavel :D

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/contato.scss
> +   padding-bottom: 4%;
toma cuidado qdo colocar padding em `%` :D

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/contato.scss
> + padding-bottom: 4%;
identaçao 🔹

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/contato.scss
> +   transition: color .4s;
aqui vc poderia fazer assim, ja que esta usando pre processador

```
.icons__a {
	....

	$:not(:last-child) {
	 	margin-right: 12px;
	}
}
```

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/contato.scss
> +}
o mesmo pro hover :D

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/experience.scss
> +.backExp{
pra classe, nao usa camel case, coloca `back-exp` :D

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/experience.scss
> +   /* top: 381%;*/
nao faça isso jamais huashuAHUShuAHUSA

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/experience.scss
> +    position: absolute;
faltou o `position: relative` no cara de cima :D

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/experience.scss
> +    opacity: 0.7;
coloca só `.7`

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/experience.scss
> +    display: flex;
tem 2 `display: flex`

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/experience.scss
> +    top: 300%;
pq 300%?

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/experience.scss
> +    position: absolute;
esta relativo com ql elemento?

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/experience.scss
> +    align-content: center;
n seria `justify-content` ? igual o que ta ali pra baixo? :P

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/experience.scss
> +    font-family: 'Lato', sans-serif;
n tem variavel pra font?

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/experience.scss
> +       position: absolute;
relativo com qual? :D

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/experience.scss
> +    margin: 0 0 0 auto;
nao poderia ser só `margin-left: auto` ?

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/experience.scss
> +    margin: 0 -6px 0 auto;
pq 0 -6 0 auto? nao poderia só ser `margin-right: -6` ?

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/experience.scss
> +    top: 55%;
tbm toma cuidado com esses top/left em %... estao relativo com quem?

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/experience.scss
> +.prestige{
prestige?

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/header.scss
> +  text-transform: uppercase;
todas as tags `<p>` vao ser uppercase? evite estilizar tags :D prefira classes

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/header.scss
> +   z-index: 9999;
9999? cheiro de gambs uahshuASAUshaHUS :{D

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/header.scss
> +  align-items: center;
pra esse àlign-items` funcionar tem que ter o `display: flex`

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/header.scss
> +
espaço hhihi

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/header.scss
> +     transition: 0.5s;
o que vai receber esse transition?

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/header.scss
> +.nav__conteudo .nav__link:not(:last-child){
esse `.nav__link` só existe na `.nav` ... entao nao precisa de hierarquia :D

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/portfolio.scss
> +        display: flex;
repetindo o `display: flex`

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/portfolio.scss
> +        align-content: center;
esse é pra alinhar o cara que é filho de um display flex

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/portfolio.scss
> +    .port a {
pq todos sao `portifolio__` e esse é `port` ? e vc tbm poderia substituir o `portifolio` por `&`

ficaria assim

```.portifolio { 
  &__link { ```

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/sobre.scss
> +  display: flex;
display flex repetido :D e esse elemento ta relativo a qual?

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/sobre.scss
> +.sobre__back {&:before {
pula linha antes do `&`

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/sobre.scss
> +$color-bar: #e91e63;
pq essas variaveis estao perdidas aqui?

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/sobre.scss
> +position: relative;
pq relative?

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/sobre.scss
> +    display: table;
table? ahusSHuAUS usa flex

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/sobre.scss
> +    $nextdeg: 90deg +  ( $increment * $i ) ;
o que é nextdeg? auhshAShuaS =D

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/sobre.scss
> + -o-transition: all 1s; /* Opera */
tira os prefixos, deixa que o gulp coloca pra vc :D

2017-11-02 00:14 UTC, andre-mendes commented on src/scss/layout/sobre.scss
> +   -webkit-transform-style: preserve-3d;
sinto cheiro de copy and paste ashuAHSuAHUhuaS :D

2017-11-03 01:31 UTC, tangriane commented on src/scss/layout/contato.scss
> +
Também não sei pq estava la, retirei!

2017-11-03 01:32 UTC, tangriane commented on src/scss/layout/contato.scss
> +.contato{
Feito!

2017-11-03 01:46 UTC, tangriane commented on src/scss/layout/contato.scss
> +   width: 100%;
essa classe nem deveria existir, já retirei!

2017-11-03 01:47 UTC, tangriane commented on src/scss/layout/contato.scss
> +.contatc{
Já tirei

2017-11-03 17:12 UTC, tangriane commented on src/scss/layout/experience.scss
> +    margin: 0 -6px 0 auto;
Corrigi!

2017-11-03 17:12 UTC, tangriane commented on src/scss/layout/experience.scss
> +    margin: 0 0 0 auto;
Corrigi !

2017-11-16 16:35 UTC, merged